# These are supported funding model platforms
github: ravindersingh
patreon: ravindersingh
open_collective: aurelinx
ko_fi: ravindersingh
tidelift: npm/aurelinx
custom: ["https://aurelinx.com/sponsor"]